# .readthedocs.yaml

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
   install:
      - method: pip
        path: .
        extra_requirements:
            - dev
   system_packages: true

sphinx:
   builder: html
   configuration: docs/conf.py
