# .readthedocs.yml

version: 2

build:
    image: latest

python:
    version: 3.6
    install:
        - method: pip
            path: "."
            extra_requirements: docs
    system_packages: true

sphinx:
    builder: html
    configuration: docs/conf.py
