# .readthedocs.yaml

version: 2

build:
    image: latest

python:
   version: 3.9
   install:
      - method: pip
        path: .
        extra_requirements:
            - dev
   system_packages: true

sphinx:
   builder: html
   configuration: docs/conf.py
