name: Documentation Request
description: Create a documentation request to help us improve
labels: ["docs"]
body:
  - type: textarea
    id: request
    attributes:
      label: Description of the request
      description: Clear and concise description of what should be documented.