name: Feature Request
description: Suggest an idea for this project
labels: ["enhancement"]
body:
  - type: textarea
    id: request
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: Clear and concise description of what the problem is.
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.