"""Deephyper analytics - hyperparameter search study documentation

usage::

    deephyper-analytics hps TEST/test_382DS/results.csv

"""

import os
import argparse
from deephyper.core.plot.jn_loader import NbEdit

HERE = os.path.dirname(os.path.abspath(__file__))


def hps_analytics(path_to_data_file, nb_name='dh-analytics-hps'):
    path_to_data_file = os.path.abspath(path_to_data_file)
    editor = NbEdit(os.path.join(HERE, 'stub/hps_analytics.ipynb'),
                    path_to_save=f"{nb_name}.ipynb")

    venv_name = os.environ.get('VIRTUAL_ENV').split('/')[-1]
    editor.setkernel(venv_name)

    editor.edit(0, "{{path_to_data_file}}", path_to_data_file)

    editor.edit(1, "{{path_to_data_file}}", f"'{path_to_data_file}'")

    editor.write()

    editor.execute()


def add_subparser(subparsers):
    subparser_name = 'hps'
    function_to_call = main

    parser_parse = subparsers.add_parser(
        subparser_name, help='Tool to generate analytics on a single HPS experiment (jupyter notebook).')
    parser_parse.add_argument('-p',
        '--path', type=str, help='A CSV file generated by the search.')
    parser_parse.add_argument('-n', '--name', type=str,
        default='dh-analytics-hps.ipynb',
        help='Name of the produced jupyter notebook.')

    return subparser_name, function_to_call


def main(path, name, *args, **kwargs):
    hps_analytics(path_to_data_file=path, nb_name=name)
