name: dh-arm-gpu
channels:
  - conda-forge
  - apple
dependencies:
  - python>=3.10
  - pip
  - msgpack-python
  - pandas
  - xgboost
  - pip:
      - numpy==1.21.4
      - -r requirements.macOS.arm64.txt
