"""The :mod:`deephyper.nas.run` sub-package provides a set of functions which can evaluates configurations generated by search algorithms of DeepHyper.
"""
from deephyper.nas.run.quick import run as quick
from deephyper.nas.run.quick2 import run as quick2
