name: Run checks

on:
  - pull_request
  - push

jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install ruff

      - name: Run linter checks with ruff
        run: ruff check

      - name: Run formatter checks with ruff
        run: ruff format --check
