name: Run checks and tests

on: 
    push:
      branches:
        - master
        - develop
        - "*redis*"
    pull_request:
      branches:
        - master
        - develop

jobs:

  tests-redis:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.13"]
        mpi: ["openmpi"]
        redis-version: ["7.4.0-v1"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}
      - name: Start Redis
        uses: supercharge/redis-github-action@1.8.0
        with:
          redis-image: redis/redis-stack-server
          redis-version: ${{ matrix.redis-version }}
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install with mpi4py
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install .[mpi,redis]

      - name: Run tests
        run: pytest  -m redis --run-marks-subset redis tests/