name: Run tests

on:
  workflow_run:
    workflows: ["Run checks"]
    types:
      - completed

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install .

      - name: Run tests with pytest
        run: pytest -m "fast or hpo"
