name: Tests Redis

on: 
    push:
      branches:
        - "*redis*"
    pull_request:
      branches:
        - master
        - develop

jobs:

  tests-redis:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        mpi: ["openmpi"]
        redis-version: ["7.4.0-v1"]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup MPI
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: ${{ matrix.mpi }}

      - name: Setup Redis-Stack
        uses: supercharge/redis-github-action@1.8.0
        with:
          redis-image: redis/redis-stack-server
          redis-version: ${{ matrix.redis-version }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: PyPI Install with MPI and Redis
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install .[mpi,redis]

      - name: Run Redis tests
        run: pytest  -m redis --run-marks-subset redis tests/

      - name: Run Redis,MPI tests
        run: pytest  -m "mpi and redis" --run-marks-subset mpi,redis tests/