name: Run tests on macOS

on:
  pull_request:
    branches: master

jobs:

  tests-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
        os: [macos-14, macos-15]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pytest
          pip install .
      - name: Run tests using pytest
        run: pytest
